### ISSUE TITLE
scroll when draw in scrollview on iOS

### ISSUE THREAD

**Issue by dioi2000** [sourcetoad/react-native-sketch-canvas#51]
https://github.com/sourcetoad/react-native-sketch-canvas/assets/33106641/19f82ece-1fe7-4c06-82b7-da2f13d5e022

android is ok but on iOS it works like this video

**Comment by iBotPeaches** [comment]
@ian-wd does this video remind you of that same issue we had? I can't remember if that was library fault or how we laid component onto page.

**Comment by iBotPeaches** [comment]
@dioi2000 - I found this as an older issue in the original package: https://github.com/terrylinla/react-native-sketch-canvas/issues/64

To be honest, we fixed it by just locking the child container using the `startStroke` and `endStroke` events that this library offers.

Either way if this works like this on Android - I'll do some research if we can prevent those events going further.

**Comment by dioi2000** [comment]
@iBotPeaches you are my life saver!

**Comment by iBotPeaches** [comment]
@dioi2000 - I could not find a way to resolve this natively in the library. You have to continue to use the events to lock scroll when interacting with component.
