### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSketchCanvas" was not found in the UIManager

### ISSUE THREAD

**Issue by arazaq917** [sourcetoad/react-native-sketch-canvas#64]
I am using react-native version 0.73.6 and  Expo 50.0.17 

<img width="336" alt="Screen Shot 2024-06-12 at 6 22 35 PM" src="https://github.com/sourcetoad/react-native-sketch-canvas/assets/58364884/26e8d209-8a5e-4ace-a263-1c031205205e">

**Comment by iBotPeaches** [comment]
Sorry you are encountering that. As our sample application is presently on RN73.x and works perfectly fine - I cannot replicate this.

I encourage you to attempt building the sample application and see if you replicate the issue - https://github.com/sourcetoad/react-native-sketch-canvas/tree/master/example
